### REDDIS ###
- name: install Redis
  ansible.builtin.command: apt-get install -y redis-server

- name: ensure Redis is running and enabled
  ansible.builtin.service:
    name: redis-server
    state: started
    enabled: yes

### POSTGRES ###
- name: install postgres
  ansible.builtin.command: apt-get install -y postgresql-14

- name: ensure postgres is running and enabled
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: yes

- name: give root login permissions to the db
  ansible.builtin.shell:
    cmd: |
      cp /etc/postgresql/14/main/pg_hba.conf /etc/postgresql/14/main/pg_hba.conf.backup &&
      sed -i "s/local   all             all                                     peer/local   all             all                                     trust/" /etc/postgresql/14/main/pg_hba.conf
      sed -i "s/local   all             postgres                                peer/local   all             postgres                                trust/" /etc/postgresql/14/main/pg_hba.conf

- name: restart postgres to lock in permission changes
  ansible.builtin.service:
    name: postgresql
    state: restarted

- name: ensure backup directory exists and has appropriate permissions
  ansible.builtin.file:
    path: /mnt/volume_missinglink_db/backup
    state: directory
    mode: "0777"

# this is disabled in all productions that aren't 'prod' in
- name: set up the cronjob to run the backup once every 6 hours
  ansible.builtin.cron:
    name: "backing up dbs every 6 hours"
    hour: "*/6"
    job: "sh {{ backup_script_dest_path }}/backup_db.sh"
    user: "root"
