### REDDIS ###
- name: install Redis
  ansible.builtin.command: apt-get install -y redis-server

- name: ensure Redis is running and enabled
  ansible.builtin.service:
    name: redis-server
    state: started
    enabled: yes

### POSTGRES ###
- name: install postgres
  ansible.builtin.command: apt-get install -y postgresql-14

- name: ensure postgres is running and enabled
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: yes

- name: give root login permissions to the db
  ansible.builtin.shell:
    cmd: |
      cp /etc/postgresql/12/main/pg_hba.conf /etc/postgresql/12/main/pg_hba.conf.backup &&
      sed -i "s/local   all             postgres                                peer/local   all             postgres                                trust/" /etc/postgresql/12/main/pg_hba.conf

- name: restart postgres to lock in permission changes
  ansible.builtin.service:
    name: postgresql
    state: restarted

- name: copy over the backup script
  ansible.builtin.template:
    src: backup_db.sh.h2
    dest: /home/deployer/backup_db.sh
    owner: root
    group: root
    mode: "0700"

- name: set up the cronjob to run the backup once every 6 hours
  ansible.builtin.cron:
    name: "backing up dbs every 6 hours"
    hour: "*/6"
    job: "sh /home/deployer/backup_db.sh"
    user: "root"
