- name: update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install common tools
  ansible.builtin.apt:
    name:
      - fail2ban
      - curl
      - git
      - jq
      - tmux
      - awscli
      - dotnet-sdk-6.0
    state: present

- name: install node
  ansible.builtin.shell:
    cmd: |
      curl -sL https://deb.nodesource.com/setup_16.x -o /tmp/nodesource_setup.sh &&
      chmod 777 /tmp/nodesource_setup.sh &&
      bash /tmp/nodesource_setup.sh &&
      apt install nodejs
