- name: update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install common tools
  ansible.builtin.apt:
    name:
      - fail2ban
      - curl
      - git
      - jq
      - tmux
      - awscli
      - nodejs
      - npm
      - dotnet-sdk-6.0
    state: present
