- name: create the deployer group
  ansible.builtin.group:
    name: deployer
    gid: 1001
    state: present

- name: create the deployer user and add it to the deployer group
  ansible.builtin.user:
    name: deployer
    uid: 1001
    group: 1001
    createhome: yes

- name: update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install common tools
  ansible.builtin.apt:
    name:
      - fail2ban
      - curl
      - jq
      - tmux
    dpkg_options: "force-confdef,force-confold,Lock::Timeout=-1"
    state: present
