apiVersion: apps/v1
kind: Deployment
metadata:
  name: awardit-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: awardit-api
  template:
    metadata:
      labels:
        app: awardit-api
    spec:
      containers:
        - name: awardit-api
          image: registry.digitalocean.com/grangeal-container-registry/awardit-api
          ports:
            - containerPort: 3001
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
      imagePullSecrets:
        - name: regcred
