---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: startertab-deployment-latest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: startertab-latest
  template:
    metadata:
      labels:
        app: startertab-latest
    spec:
      containers:
        - name: startertab
          image: docker.io/grangeal/startertab:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
      imagePullSecrets:
        - name: startertab-registry-cred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: startertab-deployment-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: startertab-qa
  template:
    metadata:
      labels:
        app: startertab-qa
    spec:
      containers:
        - name: startertab
          image: docker.io/grangeal/startertab:qa
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
      imagePullSecrets:
        - name: startertab-registry-cred
