- name: install nginx with specific dpkg options
  ansible.builtin.apt:
    name: nginx
    state: present

- name: copy over my nginx.conf file
  ansible.builtin.template:
    src: nginx.conf.h2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: "0644"

- name: ensure nginx is enabled and will start on boot
  ansible.builtin.systemd:
    name: nginx
    enabled: yes
    state: started
