- name: clone down awardit
  git:
    repo: "{{ awardit_repo_url }}"
    dest: "{{ awardit_dest_path }}"
    clone: yes
    update: yes

- name: install node modules
  ansible.builtin.shell:
    cmd: |
      cd {{ awardit_dest_path }}/api &&
      npm i

- name: setup systemd file for awardit
  ansible.builtin.template:
    src: awardit.service.j2
    dest: /etc/systemd/system/awardit.service
    owner: root
    group: root
    mode: "0644"

- name: setup .env file for awardit
  ansible.builtin.template:
    src: awardit_env.j2
    dest: "{{ awardit_dest_path }}/api/.env"
    owner: root
    group: root
    mode: "0600"

- name: enable awardit in systemd
  ansible.builtin.systemd_service:
    name: awardit
    enabled: yes
