- name: clone down awardit
  git:
    repo: "{{ awardit_repo_url }}"
    dest: "{{ awardit_dest_path }}"
    clone: yes
    update: yes

- name: install node modules
  ansible.builtin.shell:
    cmd: |
      cd {{ awardit_dest_path }}/api &&
      npm i

- name: setup systemd file for awardit
  ansible.builtin.template:
    src: awardit.service.j2
    dest: /etc/systemd/system/awardit.service
    owner: root
    group: root
    mode: "0644"

- name: copy over missinglink shell script for creating statistics
  ansible.builtin.template:
    src: missinglink-updates.sh
    dest: /home/deployer/missinglink-updates.sh
    owner: deployer
    group: deployer
    mode: "0777"

- name: setup cron job for calling missinglink backend
  ansible.builtin.cron:
    name: "call missinglink updates api endpoint"
    minute: "0,15,30,45"
    job: "sh /home/deployer/missinglink-updates.sh"
    user: "root"

- name: reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
