- name: include tasks for setting up awardit
  ansible.builtin.import_tasks: awardit.yml

- name: include tasks for setting up missinglink
  ansible.builtin.import_tasks: missinglink.yml

- name: include setting up certificates
  ansible.builtin.import_tasks: certificates.yml
