- name: import tasks for setting up awardit
  ansible.builtin.import_tasks: awardit.yml

- name: import tasks for setting up missinglink
  ansible.builtin.import_tasks: missinglink.yml

- name: import tasks for setting up umami
  ansible.builtin.import_tasks: umami.yml

- name: include setting up certificates
  ansible.builtin.import_tasks: certificates.yml

- name: reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
