- name: clone down umami
  git:
    repo: "{{ umami_repo_url }}"
    dest: "{{ umami_dest_path }}"
    clone: yes
    update: yes

- name: install pm2
  ansible.builtin.shell:
    cmd: npm install pm2 yarn -g

- name: install node modules for umami
  ansible.builtin.shell:
    cmd: |
      cd {{ umami_dest_path }} &&
      yarn install

- name: configure umami to use the local db
  ansible.builtin.shell:
    cmd: |
      cd {{ umami_dest_path }} &&
      echo DATABASE_URL=postgresql://{{ lookup('env', 'UMAMI_DATABASE_KEY') }}@localhost:5432/umami > .env

# Umami requires a db connection to build.... so the following is being done the terraform stage as a remote exec post db restoration
# keeping the below so I know what is going on

# - name: build umami
#   ansible.builtin.shell:
#     cmd: |
#       cd {{ umami_dest_path }} &&
#       export NODE_OPTIONS=--max-old-space-size=512 &&
#       cat ./.env &&
#       yarn build

# - name: start up umami
#   ansible.builtin.shell:
#     cmd: |
#       cd {{ umami_dest_path }} &&
#       pm2 start npm --name umami -- start &&
#       pm2 startup &&
#       pm2 save
