apiVersion: v1
kind: Service
metadata:
  name: awardit-api-service
spec:
  type: NodePort
  selector:
    app: awardit-api
  ports:
    - protocol: TCP
      port: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: ExternalName
  externalName: data.awardit.info
  ports:
    - protocol: TCP
      port: 2345
      targetPort: 2345
