apiVersion: v1
kind: Service
metadata:
  name: missinglink-api-service
spec:
  type: NodePort
  selector:
    app: missinglink-api
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: ExternalName
  externalName: data.missinglink.info
  ports:
    - protocol: TCP
      port: 2345
      targetPort: 2345
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: ExternalName
  externalName: data.missinglink.info
  ports:
    - protocol: TCP
      port: 2346
      targetPort: 2346
