apiVersion: v1
kind: Service
metadata:
  name: startertab-service
spec:
  type: NodePort
  selector:
    app: startertab
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: startertab-qa-service
spec:
  type: NodePort
  selector:
    app: startertab-qa
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
