apiVersion: v1
kind: Service
metadata:
  name: umami-service
spec:
  type: NodePort
  selector:
    app: umami
  ports:
    - protocol: TCP
      port: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: ExternalName
  externalName: data.missinglink.info
  ports:
    - protocol: TCP
      port: 2345
      targetPort: 2345
